---
development:
  adapter: postgresql
  host: 127.0.0.1
  port: 5432
  database: zeitgeist_development
  username: runeb
test:
  adapter: postgresql
  host: 127.0.0.1
  port: 5432
  database: zeitgeist_test
  username: runeb
